import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>.: WebLogin - Exemplo de interface login com dashboard :.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <p>Put your code here...</p>
      </main>
    </>
  )
}
